# Generated by Django 3.0.3 on 2020-04-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('adult', models.TextField(blank=True, null=True)),
                ('belongs_to_collection', models.TextField(blank=True, null=True)),
                ('budget', models.TextField(blank=True, null=True)),
                ('genres', models.TextField(blank=True, null=True)),
                ('homepage', models.TextField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imdb_id', models.TextField(blank=True, null=True)),
                ('original_language', models.TextField(blank=True, null=True)),
                ('original_title', models.TextField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('popularity', models.TextField(blank=True, null=True)),
                ('poster_path', models.TextField(blank=True, null=True)),
                ('production_companies', models.TextField(blank=True, null=True)),
                ('production_countries', models.TextField(blank=True, null=True)),
                ('release_dat', models.TextField(blank=True, null=True)),
                ('revenue', models.TextField(blank=True, null=True)),
                ('runtime', models.TextField(blank=True, null=True)),
                ('spoken_languages', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('tagline', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('video', models.TextField(blank=True, null=True)),
                ('vote_average', models.TextField(blank=True, null=True)),
                ('vote_count', models.TextField(blank=True, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('crew', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField(blank=True, null=True)),
                ('movieid', models.TextField(blank=True, null=True)),
                ('rating', models.TextField(blank=True, null=True)),
                ('timestamp', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ratings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
